#!/bin/bash

faces=(Vayalar Malabar)
styles=(Regular Bold Italic "Bold Italic")
desc_long="Malayalam script font for all languages using the Malayalam script"

export nlci=$HOME/script/tools
export src=source

pushd ${src}/archive
for ttf in ../../../../mappings/winscript/fonts/*.ttf
do
    echo "applying legacy OFL to file from $ttf"
    $HOME/script/zind/bin/legacy-ofl $ttf $(basename $ttf) 1995
done
popd

source ${nlci}/prepare.bash

source ${nlci}/metadata.bash

echo "done producing main UFO sources"

# handle an extra face with less styles
faces=(Kalyani)
styles=(Regular Italic)

rm -f ${src}/*-???*.sfd*
echo "done producing UFO sources"
