#!/usr/bin/python3

Vowels = [
    0x0D05,  # MALAYALAM LETTER A
    0x0D06,  # MALAYALAM LETTER AA
    0x0D07,  # MALAYALAM LETTER I
    0x0D08,  # MALAYALAM LETTER II
    0x0D09,  # MALAYALAM LETTER U
    0x0D0A,  # MALAYALAM LETTER UU
    0x0D0B,  # MALAYALAM LETTER VOCALIC R
    0x0D0C,  # MALAYALAM LETTER VOCALIC L
    0x0D0E,  # MALAYALAM LETTER E
    0x0D0F,  # MALAYALAM LETTER EE
    0x0D10,  # MALAYALAM LETTER AI
    0x0D12,  # MALAYALAM LETTER O
    0x0D13,  # MALAYALAM LETTER OO
    0x0D14,  # MALAYALAM LETTER AU
    0x0D5F,  # MALAYALAM LETTER ARCHAIC II
    0x0D60,  # MALAYALAM LETTER VOCALIC RR
    0x0D61,  # MALAYALAM LETTER VOCALIC LL
]

Matras = [
    0x0D3E,  # MALAYALAM VOWEL SIGN AA
    0x0D3F,  # MALAYALAM VOWEL SIGN I
    0x0D40,  # MALAYALAM VOWEL SIGN II
    0x0D41,  # MALAYALAM VOWEL SIGN U
    0x0D42,  # MALAYALAM VOWEL SIGN UU
    0x0D43,  # MALAYALAM VOWEL SIGN VOCALIC R
    0x0D44,  # MALAYALAM VOWEL SIGN VOCALIC RR
    0x0D46,  # MALAYALAM VOWEL SIGN E
    0x0D47,  # MALAYALAM VOWEL SIGN EE
    0x0D48,  # MALAYALAM VOWEL SIGN AI
    0x0D4A,  # MALAYALAM VOWEL SIGN O
    0x0D4B,  # MALAYALAM VOWEL SIGN OO
    0x0D4C,  # MALAYALAM VOWEL SIGN AU
    0x0D57,  # MALAYALAM AU LENGTH MARK
    0x0D62,  # MALAYALAM VOWEL SIGN VOCALIC L
    0x0D63,  # MALAYALAM VOWEL SIGN VOCALIC LL
    ]

Consonants = [
    0x0D15,  # MALAYALAM LETTER KA
    0x0D16,  # MALAYALAM LETTER KHA
    0x0D17,  # MALAYALAM LETTER GA
    0x0D18,  # MALAYALAM LETTER GHA
    0x0D19,  # MALAYALAM LETTER NGA
    0x0D1A,  # MALAYALAM LETTER CA
    0x0D1B,  # MALAYALAM LETTER CHA
    0x0D1C,  # MALAYALAM LETTER JA
    0x0D1D,  # MALAYALAM LETTER JHA
    0x0D1E,  # MALAYALAM LETTER NYA
    0x0D1F,  # MALAYALAM LETTER TTA
    0x0D20,  # MALAYALAM LETTER TTHA
    0x0D21,  # MALAYALAM LETTER DDA
    0x0D22,  # MALAYALAM LETTER DDHA
    0x0D23,  # MALAYALAM LETTER NNA
    0x0D24,  # MALAYALAM LETTER TA
    0x0D25,  # MALAYALAM LETTER THA
    0x0D26,  # MALAYALAM LETTER DA
    0x0D27,  # MALAYALAM LETTER DHA
    0x0D28,  # MALAYALAM LETTER NA
    0x0D29,  # MALAYALAM LETTER NNNA
    0x0D2A,  # MALAYALAM LETTER PA
    0x0D2B,  # MALAYALAM LETTER PHA
    0x0D2C,  # MALAYALAM LETTER BA
    0x0D2D,  # MALAYALAM LETTER BHA
    0x0D2E,  # MALAYALAM LETTER MA
    0x0D2F,  # MALAYALAM LETTER YA
    0x0D30,  # MALAYALAM LETTER RA
    0x0D31,  # MALAYALAM LETTER RRA
    0x0D32,  # MALAYALAM LETTER LA
    0x0D33,  # MALAYALAM LETTER LLA
    0x0D34,  # MALAYALAM LETTER LLLA
    0x0D35,  # MALAYALAM LETTER VA
    0x0D36,  # MALAYALAM LETTER SHA
    0x0D37,  # MALAYALAM LETTER SSA
    0x0D38,  # MALAYALAM LETTER SA
    0x0D39,  # MALAYALAM LETTER HA
    0x0D3A,  # MALAYALAM LETTER TTTA
    ]

Virama = [
    0x0D4D,  # MALAYALAM SIGN VIRAMA
    ]

Digits = [
    0x0D66,  # MALAYALAM DIGIT ZERO
    0x0D67,  # MALAYALAM DIGIT ONE
    0x0D68,  # MALAYALAM DIGIT TWO
    0x0D69,  # MALAYALAM DIGIT THREE
    0x0D6A,  # MALAYALAM DIGIT FOUR
    0x0D6B,  # MALAYALAM DIGIT FIVE
    0x0D6C,  # MALAYALAM DIGIT SIX
    0x0D6D,  # MALAYALAM DIGIT SEVEN
    0x0D6E,  # MALAYALAM DIGIT EIGHT
    0x0D6F,  # MALAYALAM DIGIT NINE
    ]

vowels = list(map(chr, Vowels))
matras = list(map(chr, Matras))
consonants = list(map(chr, Consonants))
h = virama = list(map(chr, Virama))[0]
digits = list(map(chr, Digits))
